service = {
    'gc': 'TradingView',
    'lb': 'Mailru Group',
    'az': 'CityBase',
    'wl': 'YouGotaGift',
    'kc': 'Vinted',
    'cn': 'Fiverr',
    'km': 'Rozetka',
    'lt': 'BitClout',
    'ip': 'Burger King',
    'pt': "Букмекерка🔥",
    'qj': 'Whoosh',
    'jf': 'Likee',
    'sf': 'SneakersnStuff',
    'lp': 'Algida', 
    'nr': 'Tosla', 
    'fs': 'Şikayet var', 
    'yi': 'Yemeksepeti',
    'hy': 'Ininal', 
    'wn': 'GameArena', 
    'ul': 'Getir', 
    'ql': 'CMTcuzdan', 
    'el': 'Bisu', 
    'pa': 'Gamekit', 
    'gx': 'Hepsiburadacom',
    'xl': 'Wmaraci', 
    'ti': 'cryptocom', 
    'cx': 'Icrypex', 
    'vn': 'Yaay', 
    'nk': 'Gittigidiyor',
    'tj': 'dbrUA',
    'full': 'Полная',
    'ce': 'mosru',
    'kf': 'Weibo',
    'ip': 'Burger King',
    'qd': 'Taobao',
    'yn': 'Allegro',
    'af': 'GalaxyWin',
    'ou': 'Gabi',
    'tt': 'Ziglu',
    'ff': 'AVON',
    'qo': 'Moneylion',
    'dn': 'Paxful',
    'pr': 'Trendyol',
    'ly': 'Olacabs',
    'vf': 'Q12 Trivia',
    'zm': 'OfferUp',
    'jh': 'PingPong',
    'fe': 'CliQQ',
    'rt': 'hily',
    'wc': 'Craigslist',
    'of': 'Urent',
    'sw': 'NCsoft',
    'vv': 'Seosprint',
    'kn': 'Verse',
    'ug': 'Fiqsy',
    'rx': 'Sheerid',
    'cw': 'PaddyPower',
    'jl': 'Hopi',
    'qh': 'Oriflame',
    'mu': 'MyMusicTaste',
    'vw': 'CoinField',
    'kl': 'kolesa.kz',
    'li': 'Baidu',
    'bf': 'Keybase',
    'kb': 'kufar',
    'll': '888casino',
    'zr': 'Papara',
    'rr': 'Wolt',
    'si': 'Cita Previa',
    'ss': 'Hezzl',
    'th': 'WestStein',
    'pf': 'pof.com',
    'py': 'Monese',
    'qe': 'GG',
    'fj': 'Potato Chat',
    'sq': 'KuCoinPlay',
    'co': 'Rediffmail',
    'tl': 'Truecaller',
    'qu': 'Agroinform',
    'lr': 'Okta',
    'px': 'Nifty',
    'dx': 'Powerkredite',
    'ib': 'Immowelt',
    'uz': 'OffGamers',
    'gd': 'Surveytime',
    'cc': 'Quipp',
    'le': 'E bike Gewinnspiel',
    'rd': 'Lenta',
    'we': 'ДругВокруг',
    'cd': 'SpotHit',
    'pp': 'Huya',
    'dh': 'eBay',
    'lw': 'MrGreen',
    'hu': 'Ukrnet',
    'qa': 'MyFishka',
    'yo': 'Amasia',
    'me': 'Line messenger',
    'il': 'IQOS',
    'zf': 'OnTaxi',
    'zh': 'Zoho',
    'iz': 'Global24',
    're': 'Coinbase',
    'ey': 'miloan',
    'ri': 'BillMill',
    'xz': 'paycell', 
    'kp': 'HQ Trivia',
    'vo': 'Brand20ua',
    'zy': 'Nttgame',
    'ji': 'Monobank',
    'wg': 'Skout',
    'gp': 'Ticketmaster',
    'cp': 'Uklon',
    'tn': 'LinkedIN',
    'sn': 'OLX',
    'st': 'Auchan',
    'rz': 'EasyPay',
    'gi': 'Hotline',
    'la': 'ssoidnet',
    'zz': 'Dent',
    'gl': 'GlobalTel',
    'cm': 'Prom',
    'de': 'Karusel',
    'df': 'Happn',
    'ya_1': 'Яндекс + переад.',
    'tw': 'Twitter',
    'tx': 'Bolt',
    'ls': 'Careem',
    'ya': 'Яндекс',
    'av_1': 'Авито + переад.',
    'ua': 'BlaBlaCar',
    'dp': 'ProtonMail',
    'yf': 'Citymobil',
    'ub': 'Uber',
    'hw': 'AliPay',
    'ds': 'Discord',
    'dt': 'Delivery Club',
    'yk': 'СпортМастер',
    'yl': 'Yalla',
    'ma': 'Mail.ru',
    'ym': 'Юла',
    'mb': 'Yahoo',
    'uk': 'Airbnb',
    'qi': '32red',
    'mg': 'Магнит',
    'yw': 'Grindr',
    'ig': 'Instagram',
    'uu': 'Wildberries',
    'qq': 'Tencent QQ',
    'mm': 'Microsoft',
    'ab': 'Alibaba',
    'qr': 'MEGA',
    'im': 'Imo',
    'ge': 'Paytm', 
    'qw': ' Qiwi',
    'za': 'JDcom',
    'mt': 'Steam',
    'am': 'Amazon',
    'an': 'Adidas',
    'et': 'Clubhouse',
    'ew': 'Nike',
    'vi': 'Viber',
    'fx_1': 'PGbonus+переад',
    'av': 'Avito',
    'vk': 'Vkontakte',
    'nf': 'Netflix',
    'rl': 'inDriver',
    'fb': 'facebook',
    'fd': 'Mamba',
    'jj': 'Aitu',
    'bd': 'Пятерочка',
    'ry': 'McDonalds',
    'jr': 'Самокат',
    'nv': 'Naver',
    'bl': 'BIGO LIVE',
    'wa': 'Вацап',
    'wb': 'WeChat',
    'nz': 'Foodpanda',
    'wf': 'YandexGo',
    'fu': 'Snapchat',
    'fx': 'PGbonus',
    'sg': 'OZON',
    'bz': 'Blizzard',
    'oi': 'Tinder',
    'gb': 'YouStar',
    'ok': 'Одноклассники',
    'wx': 'Apple',
    'ot_1': 'Любой другой + переад',
    'ot': 'Любой другой',
    'go': 'youtube,Gmail',
    'kt': 'KakaoTalk',
    'gt': 'Gett',
    'xk': 'DiDi',
    'tg': 'Telegram',
    'cy': 'РСА',
    'tk': 'МВидео',
    'xr': 'Tango',
    'lf': 'TikTok',
    'pl': 'Tango',
    'da': 'MTS CashBack',
    'pm': 'AOL',
    'ym_1': 'Юла + переад',
    'ts': 'PayPal',
    'po': 'premium.one',
}

services_new = {
    'wa' : 'wa',
    'tg' : 'tg',
    'fb': 'fb',
    'av' : 'av',
    "tw" : "tw",
    'ya' : "ya",
    "ym" : "ym",
    "ig" : "ig",
    "vk" : 'vk',
    "vi" : "vi",
    "sn" : "sn",
    "ok" : "ok",
    "df" : "happn",
    "go" : "go",
    "ls" : "ls",
    "ua" : "ua",
    "dp" : "dp",
    "ub" : "ub",
    "hw" : "hw",
    "ds" : "ds",
    "dt" : "dt",
    "yk" : "yk",
    "yl" : "yl",
    "mb" : "mb",
    "uk" : "uk",
    "yw" : "yw",
    "uu" : "uu",
    "mm" : "mm",
    "ab" : "ab",
    "qr" : "qr",
    "im" : "im",
    "am" : "am",
    "mt" : "mt",
    "et" : "clubhouse"
}

services = {
    'wa' : 'whatsapp',
    'tg' : 'telegram',
    'fb': '3223',
    'av' : 'avito',
    "tw" : "twitter",
    'ya' : "yandex",
    "ym" : "youla",
    "ig" : "instagram",
    "vk" : 'vkcom',
    "vi" : "viber",
    "sn" : "olx",
    "ok" : "odklru",
    "df" : "happn",
    "go" : "google",
    "ls" : "careem",
    "ua" : "blablacar",
    "dp" : "proton",
    "ub" : "uber",
    "hw" : "alipay",
    "ds" : "discord",
    "dt" : "deliveryclub",
    "yk" : "sportmaster",
    "yl" : "yalla",
    "mb" : "yahoo",
    "uk" : "airbnb",
    "yw" : "grindr",
    "uu" : "wildberries",
    "mm" : "microsoft",
    "ab" : "alibaba",
    "qr" : "mega",
    "im" : "imo",
    "am" : "amazon",
    "mt" : "steam",
    "et" : "clubhouse"
}

services_five = {
    'cn': 'fiverr',
    'lt': 'bitclout',
    'sf': 'sneakersnstuff',
    'tj': 'dbrUA',
    'ce': 'mosru',
    'kf': 'weibo',
    'ip': 'burgerking',
    'qd': 'taobao',
    'ff': 'avon',
    'dn': 'paxful',
    'pr': 'trendyol',
    'ly': 'Olacabs',
    'vf': 'q12trivia',
    'zm': 'offerUp',
    'jh': 'PingPong',
    'fe': 'cliqq',
    'rt': 'hily',
    'wc': 'craigslist',
    'sw': 'ncsoft',
    'vv': 'seosprint',
    'ug': 'fiqsy',
    'rx': 'sheerid',
    'cw': 'paddyPower',
    'jl': 'hopi',
    'qh': 'oriflame',
    'mu': 'mymusictaste',
    'vw': 'coinfield',
    'li': 'baidu',
    'bf': 'keybase',
    'kb': 'kufarby',
    'zr': 'papara',
    'rr': 'wolt',
    'si': 'citaprevia',
    'ss': 'hezzl',
    'th': 'weststein',
    'pf': 'pof',
    'py': 'monese',
    'qe': 'gg',
    'sq': 'kucoinplay',
    'co': 'rediffmail',
    'tl': 'truecaller',
    'qu': 'agroinform',
    'lr': 'okta',
    'px': 'nifty',
    'dx': 'powerkredite',
    'ib': 'immowelt',
    'uz': 'offgamers',
    'gd': 'surveytime',
    'cc': 'quipp',
    'rd': 'lenta',
    'we': 'drugvokrug',
    'cd': 'spothit',
    'pp': 'huya',
    'dh': 'ebay',
    'lw': 'mrgreen',
    'hu': 'ukrnet',
    'qa': 'myfishka',
    'yo': 'amasia',
    'il': 'iqos',
    'zh': 'zoho',
    'iz': 'global24',
    're': 'coinbase',
    'ey': 'miloan',
    'zy': 'nttgame',
    'ji': 'monobank',
    'wg': 'skout',
    'gp': 'ticketmaster',
    'tn': 'linkedin',
    'sn': 'olx',
    'rz': 'easypay',
    'la': 'ssoidnet',
    'gl': 'globaltel',
    'de': 'Karusel',
    'df': 'happn',
    'tw': 'twitter',
    'tx': 'bolt',
    'ls': 'careem',
    'ya': 'yandex',
    'ub': 'uber',
    'hw': 'alipay',
    'ds': 'discord',
    'mb': 'yahoo',
    'uk': 'airbnb',
    'yw': 'grindr',
    'ig': 'instagram',
    'uu': 'wildberries',
    'mm': 'microsoft',
    'ab': 'alibaba',
    'qr': 'mega',
    'im': 'imo',
    'mt': 'steam',
    'am': 'amazon',
    'an': 'adidas',
    'ew': 'nike',
    'vi': 'viber',
    'av': 'avito',
    'fb': 'facebook',
    'wa': 'whatsapp',
    'sg': 'ozon',
    'bz': 'blizzard',
    'oi': 'tinder',
    'wx': 'apple',
    'go': 'google',
    'kt': 'KakaoTalk',
    'gt': 'gett',
    'xk': 'didi',
    'xr': 'tango',
    'lf': 'tiktok',
    'pl': 'tango',
    'pm': 'aol',
    'ts': 'paypal',
    'po': 'premiumone',
}